[package]
name = "libssl-dev"
description = "OpenSSL development libraries"
homepage = "https://www.openssl.org/"
verify_command = "pkg-config --exists openssl"

[install.homebrew]
package_name = "openssl"

[install.apt]
package_name = "libssl-dev"

[install.pacman]
package_name = "openssl"

[install.dnf]
package_name = "openssl-devel"
