[package]
name = "libssl-dev"
description = "OpenSSL development libraries"
homepage = "https://www.openssl.org/"
verify_command = "pkg-config --exists openssl"

[install.homebrew]
pkg_name = "openssl"

[install.apt]
pkg_name = "libssl-dev"

[install.pacman]
pkg_name = "openssl"
