[package]
name = "pkg-config"
description = "Helper tool for compiling applications and libraries"
homepage = "https://www.freedesktop.org/wiki/Software/pkg-config/"
verify_binary = "pkg-config"

[install.homebrew]
package_name = "pkg-config"

[install.apt]
package_name = "pkg-config"

[install.pacman]
package_name = "pkgconf"

[install.dnf]
package_name = "pkgconf-pkg-config"
